# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Josip Radic
title: Freelancer (Technical Lead / Senior Developer)
email: josip@radic.co
# email_title: Email (Email title override)
phone: +385 98 623 757
# phone_title: Phone (Phone title override)
website: https://radic.co
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  josipradic
stackoverflow_username: "3307584"
linkedin_username: josip-radic-50668819
#dribbble_username: jekyll
facebook_username: radic.josip
#flickr_username: jekyll
instagram_username: josip_radich
#xing_username: jekyll
#pinterest_username: jekyll
# youtube_username: josip.radic@gmail.com
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Bitbucket
  icon: fab fa-bitbucket
  url: https://bitbucket.org/josip-radic
- title: Docker
  icon: fab fa-docker
  url: https://hub.docker.com/u/josipradic

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  An IT geek since the age of six who had an amazing opportunity to be a part of the pre-internet era experiencing the intensive technological achievements and being lucky enough to play with a wide range of technologies and meeting a bunch of amazing people in that path.

  I find myself as a highly motivated, proactive, reliable and hard-working person. An extrovert and a problem solver. Flexible to adapt in any team or work environment. Friendly, focused and calm in stressed situations.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Scopic Software
        sub_title: Technical lead / Senior Developer
        caption: January 2017 - present
        link: https://www.scopicsoftware.com
        # quote: >
        #   Short description of the company (optional)
        description: |
          - Architecting from scratch a serverless AWS solution for BigData healthcare company using a wide range of AWS service and resources, leading a team, participating and deciding in all architectural decisions
          - Working closely with Director of Engineering ensuring process policies and good quality coding standards for projects and company's clients
          - Architecture documentations, proposals, reviews
          - Reviewing projects' estimates and technical documentations, providing feedbacks and suggestions
          - Supporting the other departments
          - Participating in sales, SDLC initiatives, technical process improvements, training and mentoring
          - Performance reviews, interviewing and recruiting
          
          - Contributing in architectural and product decisions for KYC system
          - Working with DevOps creating a custom cluster solution (HA, horizontal and vertical scaling)
          - Participating in many other projects (small to big sized companies)
          - As part of the TL position I am coordinating teams, performing regular code reviews, taking care of bash automated scripts for builds and deployments, ensuring the quality of product and suggesting improvements
          - Providing extensive debugging, conclusions and performance optimization patches
          - Introducing new technologies, docker containerizations, working on an automated CICD on a high level capable of building and dispatching virtually all web related projects within Kubernetes cluster

          - Working on the KYC system which supplies reviewed, fully documented, and analyzed KYC data for legal entities and complex structures in an inherently efficient reusable digital master record format
          - Recognized as top performing developer in the team
          - Mentoring others and establishing components for easier abstraction and code extensibility
          - Participating, helping and consulting other projects within the company

          **Tech**
          - AWS, BigData, Microservices, Docker, Jenkins, Keycloak, RabbitMQ, MySQL, Galera, PostgreSQL, Oracle, HashiCorp Nomad dispatch, Terraform, Consul, Vault, Kubernetes, Rancher, Apache
          - git, Mercurial, SVN
          - NodeJS, Groovy, Java, Yii, Laravel, JS
      - layout: left
        title: Stromboli
        sub_title: Technical lead / Senior Developer
        caption: June 2009 - December 2016
        link: 
        # quote: >
        #   Short description of the company (optional)
        description: |
          - Leading a small team of developers
          - Was included in all software-wise decisions
          - Architecting solution improvements for existing software used by clients
          - Created several software prototypes as a teaser for sales
          - Version of CMS that allows admins to build their own modules
          - Created a ticketing system for incidents
          - Sales incentive app used by (at that time big) mobile phone manufacturer
          - Web email client
          - Participating in sales, sales meetings and work competitions
          - Writing a technical documentation, specification
          - Improving company's IT process

          **Responsibilities**
          - Leading a team
          - Code reviews
          - Code and storage performance optimizations
          - Technical documentation
          - Participating in sales, estimations and selling prices
          - Interviewing for development positions

          - Working with private companies and government foundations
          - Developing and maintaining already existing web apps from company's portfolio
          - Created a modular CMS and DMS apps
          - Worked on specific app solutions for the new clients

          **Tech**
          - Custom PHP frameworks, JS, MooTools, jQuery, 1kb Grid, ExtJS
          - Zend, CodeIgniter, CakePHP, Typo3
          - Joomla, Magento
      - layout: left
        title: AmiWEB (CA US)
        sub_title: Senior Developer
        caption: "2011"
        link: 
        # quote: >
        #   Short description of the company (optional)
        description: |
          - Upgrading an existing CMS with new features
          - Working on optimization of handling thousands of hosted applications
          - Made improvements pivoting unlimited lists of product fields vertically and horizontally
          - Custom made CSS framework, increased the overall compatibility between browsers

          **Tech**
          - CodeIgniter, MooTools, jQuery
          - CSS framework and 1kb grid system
      - layout: left
        title: IDB Mobile Technology
        sub_title: Developer / IT Administrator
        caption: March 2006 - July 2006
        link: 
        # quote: >
        #   Short description of the company (optional)
        description: |
          - Maintaining software for automatic bulk SMS messaging
          - Responsible for updates and new software features
          - Administrating the IT network

          **Tech**
          - Custom PHP framework and queued messaging
          - Linux
          - Windows
  - title: Education
    layout: list
    content:
      - layout: left
        title: Polytechnicum Zagrabiense
        sub_title: Master of Information technologies
        caption: 2003 - 2008
        # quote: >
        #   Short institution or course description (optional)
        # description: |
        #   Description of qualification

# Footer
footer_show_references: false
references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]